version: '3'

services:
  api:
    build:
      context: ./api
      args:
        app_env: "development"
    links:
      - 'db'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/src
      - ./src/node_modules
    tty: true
    container_name: api

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sample
    volumes:
      - './db:/config'
    ports:
      - 3306:3306
    container_name: db
